#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop acmeproxy.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/acmeproxy" ] && [ "$1" = remove ]; then
	invoke-rc.d acmeproxy stop || exit $?
fi
# End automatically added section
